spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: pcW0637dM3078VrhOK922w6cVV0I0D
    url: jdbc:mysql://123.57.20.244:3306/Graduation_project?serverTimezone=UTC
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 10MB

  webflux:
    multipart:
      max-in-memory-size: -1
  redis:
    host: localhost
server:
  port: 8080
mybatis:
  type-aliases-package: sale.ljw.clinic_administrator_background_system