import axios from 'axios';
let bases='http://localhost:8000/clinic';
let basesIp='http://192.168.1.106:8000/clinic';
export const findSexCoding = (config) => { return axios.get(`${bases}/general/findSex`,config); };
export const loginPatient = (params,config) => { return axios.post(`${bases}/loginPatient/login`,params,config); };
export const findCurrentAppointment = (params,config) => { return axios.post(`${bases}/orderByDoctor/currentAppointment`,params,config); };
export const editDoctorInformation = (params,config) => { return axios.post(`${bases}/doctorInformationByDoctor/editDoctorInformation`,params,config); };
export const editDoctorLogin = (params,config) => { return axios.post(`${bases}/doctorInformationByDoctor/editDoctorLogin`,params,config); };
export const getAppointmentNumber = (params,config) => { return axios.get(`${bases}/doctorHome/getAppointmentNumber/`+params,config); };
export const findAllDepartment = (params,config) => { return axios.post(`${bases}/department/findAllDepartment`,params,config); };
export const getDoctorListByDepartment = (params,config) => { return axios.get(`${bases}/departmentByPatient/getDoctorListByDepartment/`+params,config); };
export const getAppointmentTime = (params,config) => { return axios.post(`${bases}/orderByDoctor/getAppointmentTime` , params,config); };
export const getOnDutyHours = (params,config) => { return axios.get(`${bases}/orderByDoctor/getOnDuty/` + params,config); };
export const confirmAppointment = (params,config) => { return axios.post(`${bases}/orderByDoctor/confirmAppointment` , params,config); };
export const getAppointmentInformation = (params,config) => { return axios.post(`${bases}/departmentByPatient/getAppointmentInformation` , params,config); };
export const getPayAppointmentInformation = (params,config) => { return axios.get(`${bases}/departmentByPatient/getPayAppointmentInformation/` + params,config); };
export const getQRCode = (params,config) => { return axios.get(`${bases}/departmentByPatient/getQRCode/` + params,config); };
export const paymentStatus = (params,config) => { return axios.get(`${bases}/departmentByPatient/paymentStatus/` + params,config); };
export const payAppointment = (params,config) => { return axios.get(`${basesIp}/departmentByPatient/payAppointment/` + params,config); };
export const scanPayStatus = (params,config) => { return axios.get(`${basesIp}/departmentByPatient/scanPayStatus/` + params,config); };
export const findAllHistoryOrderForm = (params,config) => { return axios.post(`${bases}/orderByPatient/findAllHistoryOrderForm` , params,config); };
export const findOrderCompletion = (params,config) => { return axios.get(`${bases}/orderByPatient/findOrderCompletion/` + params,config); };
export const findUnpaidOrderForm = (params,config) => { return axios.post(`${bases}/orderByPatient/findUnpaidOrderForm` , params,config); };
export const getOrderInformation = (params,config) => { return axios.get(`${bases}/orderByPatient/getOrderInformation/` + params,config); };
export const payOrderBounding = (params,config) => { return axios.get(`${bases}/orderByPatient/payOrderBounding/` + params,config); };
export const getOrderInformationPaying = (params,config) => { return axios.get(`${bases}/orderByPatient/getOrderInformationPaying/` + params,config); };
export const getQRCodeOrder = (params,config) => { return axios.get(`${bases}/orderByPatient/getQRCodeOrder/` + params,config); };
export const scanPayStatusOrder = (params,config) => { return axios.get(`${basesIp}/orderByPatient/scanPayStatusOrder/` + params,config); };
export const payingOrder = (params,config) => { return axios.get(`${basesIp}/orderByPatient/payingOrder/` + params,config); };
export const refundOperationOrder = (params,config) => { return axios.get(`${bases}/orderByPatient/refundOperationOrder/` + params,config); };
export const getAllCurrentAppointment = (params,config) => { return axios.post(`${bases}/currentAppointmentByPatient/getAllCurrentAppointment` , params,config); };
export const cancelAppointment = (params,config) => { return axios.get(`${bases}/currentAppointmentByPatient/cancelAppointment/` + params,config); };
export const editPatientLogin = (params,config) => { return axios.post(`${bases}/patientInformationByPatient/editPatientLogin` , params,config); };
export const editPatientInformation = (params,config) => { return axios.post(`${bases}/patientInformationByPatient/editPatientInformation` , params,config); };
export const getRemindersNumber = (params,config) => { return axios.get(`${bases}/orderByPatient/getRemindersNumber/` + params,config); };
export const registerAccountByPatient = (params,config) => { return axios.post(`${bases}/patientInformationByPatient/registerAccountByPatient` , params,config); };
