import axios from 'axios';
let bases='http://localhost:8000/clinic';
export const findSexCoding = params => { return axios.get(`${bases}/general/findSex`); };
export const loginDoctor = params => { return axios.post(`${bases}/loginDoctor/login`,params); };
export const findHistoryAppointment = params => { return axios.post(`${bases}/orderByDoctor/historyAppointment`,params); };
export const findAllByAllDuty = params => { return axios.get(`${bases}/general/findAllByAllDuty`); };
export const findDepartmentCoding = params => { return axios.get(`${bases}/department/findDepartmentCoding`); };
export const findDutyTimeCoding = params => { return axios.get(`${bases}/general/findDutyTimeCoding`); };
export const findPayInformation = params => { return axios.get(`${bases}/general/findPayInformation`); };
export const findDrugSpecification = params => { return axios.get(`${bases}/general/findDrugSpecification`); };
export const checkOrderInformation = params => { return axios.post(`${bases}/orderByDoctor/checkOrder`,params); };
export const checkOrderDrug = params => { return axios.get(`${bases}/orderByDoctor/checkOrderDrug/`+params); };
export const getTotalPrice = params => { return axios.get(`${bases}/order/getTotalPrice/` + params); };
export const getOnDutyHours = params => { return axios.get(`${bases}/orderByDoctor/getOnDuty/` + params); };
export const getAppointmentTime = params => { return axios.post(`${bases}/orderByDoctor/getAppointmentTime` , params); };
export const confirmAppointment = params => { return axios.post(`${bases}/orderByDoctor/confirmAppointment` , params); };
export const findCurrentAppointment = params => { return axios.post(`${bases}/orderByDoctor/currentAppointment`,params); };
export const remindPatientNumber = params => { return axios.post(`${bases}/orderByDoctor/remindPatientNumber`,params); };
export const cancelAppointment = params => { return axios.post(`${bases}/orderByDoctor/cancelAppointment`,params); };
export const searchMedicinesRemotely = params => { return axios.get(`${bases}/orderByDoctor/searchMedicinesRemotely/`+params); };
export const findDrugByDrugName = params => { return axios.post(`${bases}/orderByDoctor/findDrugByDrugName`,params); };
export const addDrugByPatient = params => { return axios.post(`${bases}/orderByDoctor/addDrugByPatient`,params); };
export const removeDrug = params => { return axios.post(`${bases}/orderByDoctor/removeDrug`,params); };
export const endAppointmentByDoctor = params => { return axios.get(`${bases}/orderByDoctor/endAppointment/`+params); };
export const findDispensingInterface = params => { return axios.post(`${bases}/orderByDoctor/findDispensingInterface`,params); };
export const dispensingMedicine = params => { return axios.post(`${bases}/orderByDoctor/dispensingMedicine`,params); };
export const editDoctorInformation = params => { return axios.post(`${bases}/doctorInformationByDoctor/editDoctorInformation`,params); };
export const editDoctorLogin = params => { return axios.post(`${bases}/doctorInformationByDoctor/editDoctorLogin`,params); };
